### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by rqy2002** [Qv2ray/Qv2ray#1720] opened 2023-07-10 16:28 UTC
为啥你们要搞一个叫做A()的宏还不给他undef掉 这玩意和我 `/usr/include` 里某个库冲突了,
```
In file included from /home/TsingChih/GitRepos/Qv2ray/src/base/Qv2rayLog.hpp:3,
                 from /home/TsingChih/GitRepos/Qv2ray/src/base/Qv2rayBase.hpp:13,
                 from /home/TsingChih/GitRepos/Qv2ray/qv2ray_baselib_autogen/4RDSIAVZGI/../../src/components/latency/LatencyTest.hpp:2,
                 from /home/TsingChih/GitRepos/Qv2ray/qv2ray_baselib_autogen/4RDSIAVZGI/moc_LatencyTest.cpp:10,
                 from /home/TsingChih/GitRepos/Qv2ray/qv2ray_baselib_autogen/mocs_compilation.cpp:4:
/usr/include/absl/container/internal/inlined_vector.h: In constructor ‘absl::lts_20230125::inlined_vector_internal::Storage<T, N, A>::Storage()’:
/home/TsingChih/GitRepos/Qv2ray/src/base/Qv2rayLog.hpp:17:29: error: expected primary-expression before ‘,’ token
   17 | #define ___LOG_EXPAND(___x) , QPair<std::string, decltype(___x)>(std::string(#___x), [&] { return ___x; }())
      |                             ^
/home/TsingChih/GitRepos/Qv2ray/src/base/Qv2rayLog.hpp:17:63: error: expected primary-expression before ‘)’ token
   17 | #define ___LOG_EXPAND(___x) , QPair<std::string, decltype(___x)>(std::string(#___x), [&] { return ___x; }())
      |                                                               ^
/home/TsingChih/GitRepos/Qv2ray/src/base/Qv2rayLog.hpp:17:64: error: template argument 2 is invalid
   17 | #define ___LOG_EXPAND(___x) , QPair<std::string, decltype(___x)>(std::string(#___x), [&] { return ___x; }())
      |                                                                ^
make[2]: *** [CMakeFiles/qv2ray_baselib.dir/build.make:97: CMakeFiles/qv2ray_baselib.dir/qv2ray_baselib_autogen/mocs_compilation.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:146: CMakeFiles/qv2ray_baselib.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```
因为/usr/include/absl/container/internal/inlined_vector.h里有一个地方写了`A()`

**Comment by zedifen** [comment] 2023-07-10 19:12
Can you elaborate us with more build info, like your CMake options or more error log? I don't think an error like this is caused by the library or the software itself, since it has been build successfully and widely used for quite a long time.

**Comment by zedifen** [comment] 2023-07-10 19:20
By the way, I'd suggest users adopt other projects, or just use the command-line tools, since this Qv2ray (i.e. Qv2ray/Qv2ray, situation of other forks might be better) has not been actively maintained recently.

**Comment by zedifen** [comment] 2023-07-10 19:36
And if by any chances you insists on using an GUI fronted and it has to be Qv2ray, there's a [Shadowsocks-NET/Qv2ray](https://github.com/Shadowsocks-NET/Qv2ray) fork you can refer to. This fork supports v2ray-core v5 as well as v2ray-rust, etc. You can follow the build steps in the workflow file within the repo and see if things work out fine.

**Comment by moodyhunter** [comment] 2023-07-11 02:07
(probably) fixed in https://github.com/Qv2ray/Qv2ray/commit/b3080564809dd8aef864a54ca1b79f0984fe986b

**Closed as completed** 2024-05-31 15:41 UTC
Labels: Bugs
