### ISSUE TITLE
Qv2ray crashed when testing latency of subcriptions

### ISSUE THREAD

**Issue by FantasqueX** [Qv2ray/Qv2ray#661] opened 2020-06-07 06:36 UTC
**Briefly describe this bug：**
Qv2ray crashed when testing latency of subcriptions.
**How can I trigger this bug：**

1. Right click one subcriiption
2. Click test latency

**What is expected to happen**
Not crashed.

**Screenshots**
If appropriate, please attach some screenshots.

Here is the result of strace when crashed.
![qv_tst](https://user-images.githubusercontent.com/46747123/83962012-c418ab80-a8cb-11ea-9ad6-b7c1892696dc.png)
**System Information**

 - OS Type: (Windows, Linux or macOS)
 - Built from the source or download from the release?
 - Version string in the Preferences Window

**Version 2.5.0
(Official Build) 5.6.12-arch1-1 x86_64 
Built from ArchLinuxCN - Stable**

 **Affected Qv2ray installation source**
 
- ArchLinuxCN - Stable
- ArchLinuxCN - Dev-git
- ArchLinux AUR - Stable
- ArchLinux AUR - Development
- Fedora - Stable
- Fedora - Preview
- openSUSE - Stable
- openSUSE - Preview
- Flathub
- Snap
- Homebrew Cask
- Scoop
- Chocolatey
- Compile manually
- Github Release

**Other Info**

You may want to write anything if you think it helps us to fix the bug.

*Please hide your server address and UUID if you wish to post the vmess string or your connection setting.*

**Comment by DuckSoft** [comment] 2020-06-07 06:42
@FantasqueX You may want to attach a minidump/coredump to help us reproduce this problem.

**Comment by FantasqueX** [comment] 2020-06-07 07:24
@DuckSoft 
Here is the journalctl log after crash.
https://pastebin.com/jLwLGJ8e
I just don't know where to find a minidump/coredump.

**Comment by DuckSoft** [comment] 2020-06-07 07:26
https://jlk.fjfi.cvut.cz/arch/manpages/man/coredumpctl.1

**Comment by FantasqueX** [comment] 2020-06-07 07:51
> https://jlk.fjfi.cvut.cz/arch/manpages/man/coredumpctl.1

Qv2ray was not listed in the result of command "coredumpctl list"

Here is the screenshot of "Application is not responding"
![qv_error](https://user-images.githubusercontent.com/46747123/83963190-9edd6a80-a8d6-11ea-9b1a-9a57218b4ca0.png)

**Comment by DuckSoft** [comment] 2020-06-09 09:41
Cannot reproduce. That was sad. It works on my machine.
Closing this since we cannot reproduce the problem, nor can we learn something useful.

**Closed by DuckSoft** 2020-06-09 09:41 UTC
Labels: Bugs, help wanted
