### ISSUE TITLE
Feature Request: add server list sorting preference to configuration

### ISSUE THREAD

**Issue by s-kk** [Qv2ray/Qv2ray#849] opened 2020-07-31 11:59 UTC
**Is your feature request related to a problem? Please describe.**
The current version of Qv2ray will not save my sorting preference (e.g. 'By connection name, A-Z'). I would have to re-select the option every time I start Qv2ray client. 

**Describe the solution you'd like**
Adding server list sorting preference to configuration store. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by DuckSoft** [comment] 2020-07-31 12:01
duplicate of #843. merged.

**Closed** 2020-07-31 12:01 UTC
Labels: NewFeature
